name: arfantournament
description: Ultimate Gaming App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # YAHAN BADLAV KARO: 5.1.0 ki jagah 6.1.0 ya latest dalo
  google_fonts: ^6.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
